DROP DATABASE IF EXISTS racker;
CREATE DATABASE racker;
USE racker;

DROP TABLE IF EXISTS peers;
CREATE TABLE peers (
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	infohash	VARCHAR(40), 
	peerid 		VARCHAR(40), 
	downloaded 	BIGINT UNSIGNED, 
	bleft 		BIGINT UNSIGNED, 
	uploaded 	BIGINT UNSIGNED, 
	ipv4 		INT UNSIGNED, 
	ipv6		VARCHAR(16),
	idkey 		INT UNSIGNED, 
	port 		SMALLINT UNSIGNED,
	PRIMARY KEY ( infohash,peerid)
);
